name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 40.81.28.236
          username: azureuser
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/azureuser
            if [ ! -d "visual-recipes" ]; then
              git clone https://github.com/27-Maryam/visual-recipes.git
            fi
            cd visual-recipes
            git pull origin main
            sudo rm -rf /var/www/html/*
            sudo cp -r frontend/* /var/www/html/
            sudo systemctl restart apache2