name: Deploy Website to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd visual-recipes
          git pull origin main
          sudo cp -r frontend/* /var/www/html/
          sudo systemctl restart nginx